USE [master]
GO

CREATE DATABASE [Therapist]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Терапевт', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Терапевт.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Терапевт_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Терапевт_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Therapist] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Therapist].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Therapist] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Therapist] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Therapist] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Therapist] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Therapist] SET ARITHABORT OFF 
GO
ALTER DATABASE [Therapist] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Therapist] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Therapist] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Therapist] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Therapist] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Therapist] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Therapist] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Therapist] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Therapist] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Therapist] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Therapist] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Therapist] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Therapist] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Therapist] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Therapist] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Therapist] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Therapist] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Therapist] SET RECOVERY FULL 
GO
ALTER DATABASE [Therapist] SET  MULTI_USER 
GO
ALTER DATABASE [Therapist] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Therapist] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Therapist] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Therapist] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Therapist] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Therapist', N'ON'
GO
ALTER DATABASE [Therapist] SET QUERY_STORE = OFF
GO
USE [Therapist]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [Therapist]
GO
/****** Object:  Table [dbo].[Accounts]    Script Date: 07.05.2018 21:45:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Accounts](
	[AccountId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AccountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Admission]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admission](
	[Талон] [nvarchar](50) NOT NULL,
	[Диагноз] [nchar](10) NULL,
	[Дата_посещения] [nchar](10) NULL,
	[Время_посещения] [nchar](10) NULL,
 CONSTRAINT [PK_Прием] PRIMARY KEY CLUSTERED 
(
	[Талон] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Diagnosis]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Diagnosis](
	[Наименование_Диагноза] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Диагноз] PRIMARY KEY CLUSTERED 
(
	[Наименование_Диагноза] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Doctor]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doctor](
	[ID_врача] [nvarchar](50) NOT NULL,
	[ФИО] [nvarchar](50) NULL,
	[Должность] [nvarchar](50) NULL,
	[Телефон] [int] NULL,
 CONSTRAINT [PK_Врач] PRIMARY KEY CLUSTERED 
(
	[ID_врача] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patients]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patients](
	[PatientId] [int] IDENTITY(1,1) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[Birthday] [nvarchar](50) NOT NULL,
	[Gender] [nchar](10) NOT NULL,
	[Home_address] [nvarchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PatientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Shedule]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shedule](
	[ID_врача] [nvarchar](50) NOT NULL,
	[Рабочий_день] [nchar](10) NULL,
	[Смена] [nchar](10) NULL,
	[Время_работы] [int] NULL,
 CONSTRAINT [PK_График_работы] PRIMARY KEY CLUSTERED 
(
	[ID_врача] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Visits]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Visits](
	[VisitId] [int] IDENTITY(1,1) NOT NULL,
	[PatientId] [int] NULL,
	[DateOfVisit] [datetime] NOT NULL,
	[Text] [nvarchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[VisitId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Diagnosis]  WITH CHECK ADD  CONSTRAINT [FK_Диагноз_Врач] FOREIGN KEY([Наименование_Диагноза])
REFERENCES [dbo].[Doctor] ([ID_врача])
GO
ALTER TABLE [dbo].[Diagnosis] CHECK CONSTRAINT [FK_Диагноз_Врач]
GO
ALTER TABLE [dbo].[Doctor]  WITH CHECK ADD  CONSTRAINT [FK_Врач_График_работы] FOREIGN KEY([ID_врача])
REFERENCES [dbo].[Shedule] ([ID_врача])
GO
ALTER TABLE [dbo].[Doctor] CHECK CONSTRAINT [FK_Врач_График_работы]
GO
ALTER TABLE [dbo].[Doctor]  WITH CHECK ADD  CONSTRAINT [FK_Врач_Прием] FOREIGN KEY([ID_врача])
REFERENCES [dbo].[Admission] ([Талон])
GO
ALTER TABLE [dbo].[Doctor] CHECK CONSTRAINT [FK_Врач_Прием]
GO
ALTER TABLE [dbo].[Shedule]  WITH CHECK ADD  CONSTRAINT [FK_График_работы_Прием] FOREIGN KEY([ID_врача])
REFERENCES [dbo].[Admission] ([Талон])
GO
ALTER TABLE [dbo].[Shedule] CHECK CONSTRAINT [FK_График_работы_Прием]
GO
ALTER TABLE [dbo].[Visits]  WITH CHECK ADD FOREIGN KEY([PatientId])
REFERENCES [dbo].[Patients] ([PatientId])
GO
/****** Object:  StoredProcedure [dbo].[RegisterProcedure]    Script Date: 07.05.2018 21:45:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[RegisterProcedure]  
   @username nvarchar(50),  
   @password nvarchar(50),  
   @errorMessage nvarchar(500) OUTPUT  
AS  
BEGIN  

	IF((SELECT count(1) FROM [Accounts] WHERE Username=@username) = 1)
	BEGIN
		select @errorMessage = 'Ошибка, пользователь с таким именем пользователя уже есть.'
	END
	ELSE
	BEGIN
		Insert into Accounts(Username,Password) values(@username, @password)
		select @errorMessage  = ''
	END

END  
GO
USE [master]
GO
ALTER DATABASE [Therapist] SET  READ_WRITE 
GO
